In [1]:
import pandas as pd

In [5]:
jobs = pd.read_csv('jobs2.csv')

In [6]:
jobs.tail()

,Id,Created_date,Due_date,User_id,Payment_type,Budget,Job_title,Category,Subcategory,Job_description,...,No_of_quotes,Link_of_quoters,No_of_Premium_quotes,Link_of_premium_quoters,No_of_inviited,Link_of_invited_freelancers,No_of_Hired,Link_of_hired_freelancers,Min_budget,Job_cluster_id
2681,2682,"Sep 30, 2015","December 31, 2023",2056,Fixed Price,[' $500-$1k'],"Need a Custom, Print-Ready Folder Design",Design & Art,NaN,I need a presentation folder designed for an e...,...,101.0,['https://www.guru.com/freelancers/live-deftso...,1.0,[],0.0,[],0.0,[],NaN,0
2682,2683,2021-01-02 17:22:14.996647,NaN,8052,NaN,NaN,Content writer and translator for kids app,wt,NaN,yuyu,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2683,2684,2021-01-02 20:26:19.992502,NaN,8054,NaN,NaN,Data Scientist for Healthcare Domain,pd,NaN,machine learning engineer and data scientist,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2684,2685,2021-01-02 20:34:55.197537,NaN,8054,NaN,NaN,Full Stack web developer for ecommerce website,pd,NaN,fullstack web developer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2685,2686,2021-01-03 08:03:02.315451,NaN,8055,NaN,NaN,Front end web developer for ecommerce website,pd,NaN,front end web developer needed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [9]:
print(jobs[jobs['Id'] == 2686]['Skills'].values[0])

['html', 'css', 'sass', 'javascript', 'reactjs']

In [134]:
#self.jobs.append({'Id':job.id, 'Created_date':job.date, 'User_id':job.user_id, 'Payment_type':job.payment_type, 'Budget':job.budget, 'Job_title':job.title, 'Category':job.category, 'Subcategory':job.subcategory, 'Job_description':job.description, 'Skills':job.skills, 'Link_of_quoters':job.links_quoters, 'Link_of_invited_freelancers':job.links_invited, 'Link_of_hired_freelancers':job.links_hired, 'Min_budget':job.min_budget, 'Job_cluster_id':job.job_cluster_id}, ignore_index=True)
#self.jobs.to_csv(self.jobs_file)
#self.log_writer.log(self.processLog, 'Failed to read jobs data.')

In [ ]:
row = [2688, ]
row = pd.Series([])

In [135]:
new_cols = list(jobs.drop(['Unnamed: 0', 'Due_date', 'Name_of_employer', 'Link_of_employer', 'Employer_id', 'No_of_quotes', 'No_of_Premium_quotes', 'Link_of_premium_quoters', 'No_of_inviited', 'No_of_Hired'], axis=1).columns)

In [136]:
jobs = jobs[new_cols]

In [137]:
jobs['Min_budget'] = ''

In [138]:
jobs['Job_cluster_id'] = 0

In [139]:
jobs = jobs.drop(2681).copy().reset_index(drop=True)

In [140]:
jobs.tail()

,Unnamed: 0.1,Id,Created_date,User_id,Payment_type,Budget,Job_title,Category,Subcategory,Job_description,Skills,Link_of_quoters,Link_of_invited_freelancers,Link_of_hired_freelancers,Job_cluster_id,Min_budget
2677,2677.0,2678,"Feb 11, 2017",2058,Hourly,"[' No rate specified ', ' 10-30 hrs/wk ', ' 6+...",Help create networks from RNA Seq. data,Other,NaN,Patient Tutor to teach Time Series Cell Cycle ...,"['Bioinformatics', 'Biological Systems', 'Bios...","['https://www.guru.com/freelancers/khurram-m',...",[],[],0,
2678,2678.0,2679,"Dec 14, 2016",2060,Hourly,"[' $5 - $10 ', ' 30+ hrs/wk ', ' 6+ months']",SEO my site who sell instagram followers,Sales & Marketing,NaN,Project Description\n\nI need my website showi...,"['SEO', 'Smo', 'Social Media Marketing']",['https://www.guru.com/freelancers/bonzai-crea...,[],[],0,
2679,2679.0,2680,"Nov 21, 2016",2061,Fixed Price or Hourly,[],Indonesian (id_id) Longplay 2020-Q4,Writing & Translation,Copywriting,Linguistix Tank Inc. is seeking 100 native/flu...,"['Training', 'Typing', 'Indonesian Translation']",['https://www.guru.com/freelancers/raheela-khu...,['https://www.guru.com/freelancers/raheela-khu...,[],0,
2680,2680.0,2681,"Mar 14, 2016",2058,Hourly,"[' No rate specified ', ' 10-30 hrs/wk ', ' 6+...",Analyzing microarray time series data,Other,NaN,Help in analyzing yeast microarray time series...,['Bioinformatics'],['https://www.guru.com/freelancers/yesesri-che...,[],[],0,
2681,NaN,2683,2021-01-02 14:16:50.719882,8049,NaN,NaN,Data Scientist for Healthcare Domain,pd,NaN,gwgtg,python,NaN,NaN,NaN,0,

In [141]:
jobs['Id'] = (jobs.index.values+1)

In [142]:
jobs.tail()

,Unnamed: 0.1,Id,Created_date,User_id,Payment_type,Budget,Job_title,Category,Subcategory,Job_description,Skills,Link_of_quoters,Link_of_invited_freelancers,Link_of_hired_freelancers,Job_cluster_id,Min_budget
2677,2677.0,2678,"Feb 11, 2017",2058,Hourly,"[' No rate specified ', ' 10-30 hrs/wk ', ' 6+...",Help create networks from RNA Seq. data,Other,NaN,Patient Tutor to teach Time Series Cell Cycle ...,"['Bioinformatics', 'Biological Systems', 'Bios...","['https://www.guru.com/freelancers/khurram-m',...",[],[],0,
2678,2678.0,2679,"Dec 14, 2016",2060,Hourly,"[' $5 - $10 ', ' 30+ hrs/wk ', ' 6+ months']",SEO my site who sell instagram followers,Sales & Marketing,NaN,Project Description\n\nI need my website showi...,"['SEO', 'Smo', 'Social Media Marketing']",['https://www.guru.com/freelancers/bonzai-crea...,[],[],0,
2679,2679.0,2680,"Nov 21, 2016",2061,Fixed Price or Hourly,[],Indonesian (id_id) Longplay 2020-Q4,Writing & Translation,Copywriting,Linguistix Tank Inc. is seeking 100 native/flu...,"['Training', 'Typing', 'Indonesian Translation']",['https://www.guru.com/freelancers/raheela-khu...,['https://www.guru.com/freelancers/raheela-khu...,[],0,
2680,2680.0,2681,"Mar 14, 2016",2058,Hourly,"[' No rate specified ', ' 10-30 hrs/wk ', ' 6+...",Analyzing microarray time series data,Other,NaN,Help in analyzing yeast microarray time series...,['Bioinformatics'],['https://www.guru.com/freelancers/yesesri-che...,[],[],0,
2681,NaN,2682,2021-01-02 14:16:50.719882,8049,NaN,NaN,Data Scientist for Healthcare Domain,pd,NaN,gwgtg,python,NaN,NaN,NaN,0,

In [29]:
jobs = jobs.append({'Id':2683, 'Created_date':'January 2, 2021', 'User_id':1111111, 'Payment_type':'', 'Budget':'', 'Job_title':'', 'Category':'', 'Subcategory':'', 'Job_description':'', 'Skills':'', 'Link_of_quoters':'', 'Link_of_invited_freelancers':'', 'Link_of_hired_freelancers':'', 'Min_budget':'', 'Job_cluster_id':'0'}, ignore_index=True)

In [30]:
jobs

,Id,Created_date,Due_date,User_id,Payment_type,Budget,Job_title,Category,Subcategory,Job_description,...,No_of_quotes,Link_of_quoters,No_of_Premium_quotes,Link_of_premium_quoters,No_of_inviited,Link_of_invited_freelancers,No_of_Hired,Link_of_hired_freelancers,Min_budget,Job_cluster_id
0,1,"December 04, 2020","January 02, 2021",1,Fixed Price,[' $5k-$10k'],"Looking for ""NetSuite"" Part-Time Trainer",Education & Training,Information Technology,"Currently, we are Looking for ""Oracle Netsuite...",...,0.0,[],0.0,[],14.0,['https://www.guru.com/freelancers/netsuite-fr...,0.0,[],NaN,0
1,2,"December 04, 2020","December 11, 2020",2,Fixed Price,[' Under $250'],developing app for language translator,Programming & Development,Web Development & Design,Need an app to convert a youtube script from o...,...,0.0,[],0.0,[],0.0,[],0.0,[],NaN,0
2,3,"December 04, 2020","January 02, 2021",3,Fixed Price or Hourly,[],React Js Developers Needed,Programming & Development,Web Development & Design,"Hi,\nI need 2 React js developers having atlea...",...,20.0,['https://www.guru.com/freelancers/yao-tingche...,1.0,['https://www.guru.com/freelancers/yao-tingchen'],0.0,[],0.0,[],NaN,0
3,4,"December 04, 2020","January 02, 2021",4,Fixed Price,[' Under $250'],I have minimal issues with my website,Programming & Development,Web Development & Design,"Hello there, \n\nIt's vue larvel website, it's...",...,13.0,['https://www.guru.com/freelancers/amazon-soft...,0.0,[],3.0,['https://www.guru.com/freelancers/ahmed-s-hel...,0.0,[],NaN,0
4,5,"December 04, 2020","January 02, 2021",5,Fixed Price,[' $500-$1k'],Wordpress Site Customization,Programming & Development,Web Development & Design,PLEASE DO NOT RESPOND TO THIS PROJECT WITH A C...,...,13.0,['https://www.guru.com/freelancers/amazon-soft...,0.0,[],0.0,[],0.0,[],NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2685,2686,2021-01-02 18:47:04.087347,NaN,8054,NaN,NaN,Digital Marketing and Social Media Management,sm,NaN,digital marketing,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2686,2687,2021-01-02 18:56:44.154082,NaN,8054,NaN,NaN,Graphic Designer for Fashion Website,da,NaN,graphics design,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2687,2683,"January 2, 2021",NaN,1111111,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2688,2683,"January 2, 2021",NaN,1111111,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2689,2683,"January 2, 2021",NaN,1111111,,,,,,,...,NaN,,NaN,NaN,NaN,,NaN,,,0

In [29]:
import os
os.remove('jobs (copy).csv')

In [31]:
jobs.to_csv('jobs2.csv', index=False)

In [12]:
jobs.drop(jobs.columns[jobs.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)

In [13]:
jobs

,Id,Created_date,Due_date,User_id,Payment_type,Budget,Job_title,Category,Subcategory,Job_description,...,No_of_quotes,Link_of_quoters,No_of_Premium_quotes,Link_of_premium_quoters,No_of_inviited,Link_of_invited_freelancers,No_of_Hired,Link_of_hired_freelancers,Min_budget,Job_cluster_id
0,1,"December 04, 2020","January 02, 2021",1,Fixed Price,[' $5k-$10k'],"Looking for ""NetSuite"" Part-Time Trainer",Education & Training,Information Technology,"Currently, we are Looking for ""Oracle Netsuite...",...,0.0,[],0.0,[],14.0,['https://www.guru.com/freelancers/netsuite-fr...,0.0,[],NaN,0
1,2,"December 04, 2020","December 11, 2020",2,Fixed Price,[' Under $250'],developing app for language translator,Programming & Development,Web Development & Design,Need an app to convert a youtube script from o...,...,0.0,[],0.0,[],0.0,[],0.0,[],NaN,0
2,3,"December 04, 2020","January 02, 2021",3,Fixed Price or Hourly,[],React Js Developers Needed,Programming & Development,Web Development & Design,"Hi,\nI need 2 React js developers having atlea...",...,20.0,['https://www.guru.com/freelancers/yao-tingche...,1.0,['https://www.guru.com/freelancers/yao-tingchen'],0.0,[],0.0,[],NaN,0
3,4,"December 04, 2020","January 02, 2021",4,Fixed Price,[' Under $250'],I have minimal issues with my website,Programming & Development,Web Development & Design,"Hello there, \n\nIt's vue larvel website, it's...",...,13.0,['https://www.guru.com/freelancers/amazon-soft...,0.0,[],3.0,['https://www.guru.com/freelancers/ahmed-s-hel...,0.0,[],NaN,0
4,5,"December 04, 2020","January 02, 2021",5,Fixed Price,[' $500-$1k'],Wordpress Site Customization,Programming & Development,Web Development & Design,PLEASE DO NOT RESPOND TO THIS PROJECT WITH A C...,...,13.0,['https://www.guru.com/freelancers/amazon-soft...,0.0,[],0.0,[],0.0,[],NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2684,2685,2021-01-02 18:41:21.597227,NaN,8054,NaN,NaN,Content writer and translator for kids app,wt,NaN,content writing and translation required,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2685,2686,2021-01-02 18:47:04.087347,NaN,8054,NaN,NaN,Digital Marketing and Social Media Management,sm,NaN,digital marketing,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2686,2687,2021-01-02 18:56:44.154082,NaN,8054,NaN,NaN,Graphic Designer for Fashion Website,da,NaN,graphics design,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2687,2683,"January 2, 2021",NaN,1111111,,,,,,,...,NaN,,NaN,NaN,NaN,,NaN,,,0
2688,2683,"January 2, 2021",NaN,1111111,,,,,,,...,NaN,,NaN,NaN,NaN,,NaN,,,0

In [19]:
jobs.to_csv('jobs2.csv')

In [2]:
import string
from stop_words import get_stop_words
stop_words = get_stop_words('english')
def preProcess(skills):
    if isinstance(skills, list):
        s = ' '.join(skills)
    else:
        s = skills
    table = str.maketrans(dict.fromkeys(string.punctuation))
    new_s = s.translate(table)
    new_s = new_s.replace('\n', ' ')
    new_s = new_s.replace('  ', ' ')
    new_s = [x for x in new_s.lower().split() if len(x) > 1 and x not in stop_words]
    return new_s

ModuleNotFoundError: No module named 'stop_words'

In [6]:
preProcess('css')

NameError: name 'stop_words' is not defined